appname: NeuralQA

ui:
  queryview:
    intro:
      title: "NeuralQA: Question Answering on Large Datasets"
      subtitle: "NeuralQA is an interactive tool for question answering (passage retrieval + document reading). You can manually provide a passage or select a search index from (e.g. case.law ) dataset under the QA configuration settings below. To begin, type in a question query below."
      disclaimer: " .. "
    views:
      intro: True
      advanced: True # if false, default retriever/reader settings will be used.
      samples: True # show/hide sample question answer pairs
      passages: True # show/hide passages which are retrieved
      explanations: True # show/hide explanations button
      allanswers: True # show all answers or just the best answer (based on probability score)
    options:
      stride:
        title: Token Stride
        selected: 0
        options:
          - name: 0
            value: 0
          - name: 50
            value: 50
          - name: 100
            value: 100
          - name: 200
            value: 200
      maxpassages:
        title: Passages
        selected: 5
        options:
          - name: 5
            value: 5
          - name: 10
            value: 10
          - name: 15
            value: 15
      highlightspan:
        title: IR Highlight Span
        selected: 250
        options:
          - name: 150
            value: 150
          - name: 250
            value: 250
          - name: 350
            value: 350
          - name: 450
            value: 450
          - name: 650
            value: 650

  header:
    appname: NeuralQA
    appdescription: Question Answering on Large Datasets

# server:
#   host: localhost
#   port: 3008
retriever:
  title: Retriever
  selected: manual
  options:
    - name: Manual
      value: manual

      # - name: Case Law
      #   value: cases
      #   host: localhost
      #   port: 9200
      #   username: None
      #   password: None
      #   type: elasticsearch
      # - name: Supreme Court
      #   value: supremecourt
      #   host: localhost
      #   port: 9200
      #   username: None
      #   password: None
      #   type: elasticsearch
  readtopn: 0
  relsnip: true

reader:
  title: Reader
  selected: twmkn9/distilbert-base-uncased-squad2
  options:
    - name: DistilBERT SQUAD2
      value: twmkn9/distilbert-base-uncased-squad2
      type: distilbert
    # - name: BERT SQUAD2
    #   value: deepset/bert-base-cased-squad2
    #   type: bert
  # - bertlargesquad2:
  #   name: distillbertsquad1
  #   path: deepset/bert-large-uncased-whole-word-masking-squad2
  #   type: bert
  #   enabled: False

expander:
  - maskedlm:
    name: maskedlm
    path: pathtomaskedlm
    enabled: True
  - word2vec:
    name: word2vec
    path: pathtoword2vecmodel
    enabled: True
