name: docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      # Standard drop-in approach that should work for most people.
      - uses: victordibia/neuralqa@master
        with:
          docs-folder: "docs/"
      # Example of using a custom build-command.
      - uses: victordibia/neuralqa@master
        with:
          build-command: "sphinx-build -b html . _build"
          docs-folder: "docs2/"
      # Grabbing custom dependencies and building as a pdf.
      - uses: victordibia/neuralqa@master
        with:
          pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
          build-command: "make latexpdf"
          docs-folder: "docs2/"
      # Great extra actions to compose with:
      # Create an artifact of the html output.
      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationHTML
          path: docs/_build/html/
      # Create an artifact out of the previously built pdf.
      - uses: actions/upload-artifact@v1
        with:
          name: Documentation
          path: docs2/_build/latex/pdfexample.pdf
